version: '3.1'
services:
    mongo:
        image: mongo:3.6.1
        ports:
        - 27017:27017    
        restart: always
        command: --smallfiles    
        container_name: app_mongodb_c
        volumes:
        - ~/dockerdata/mongodb:/data/db      
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: example

    express:
        image: thestephenramsay/explore-edinburgh-server
        restart: always
        ports:
        - 8080:8080
        environment:
            ME_CONFIG_MONGODB_ADMINUSERNAME: root
            ME_CONFIG_MONGODB_ADMINPASSWORD: example

    frontend:
        image: stephenbit/explore-edinburgh-frontend
        build: ./client
        restart: always
        # environment:
        #     - REACT_APP_GOOGLE_KEY
        ports:
            # - "5001:80"
        - "80:80"
        # networks:
        #     - daddy-net
        # depends_on:
        #     - backend
        volumes:
            - ./nginx.conf:/etc/nginx/nginx.conf

    # db:
    #     image: yourmongoimage

