version: '3.1'
services:
    mongo:
        image: mongo:3.6.1
        ports:
            - "27017:27017"    
        restart: always
        command: --smallfiles    
        # container_name: mongodb_container
        volumes:
            - ~/dockerdata/mongodb:/data/db      
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: example
        networks:
            - explore-net

    server:
        image: stephenbit/explore-edinburgh-server
        restart: always
        ports:
            - "8080:8080"
        environment:
            MONGODB_ADMINUSERNAME: root
            MONGODB_ADMINPASSWORD: example
        networks:
            - explore-net
        depends_on:
            - mongo

    client:
        image: stephenbit/explore-edinburgh-client
        build: ./client
        restart: always
        # environment:
        ports:
            - "80:80"
        depends_on:
            - server
        # volumes:
        #     - ./nginx.conf:/etc/nginx/nginx.conf

networks:
    explore-net:

