use explore_edinburgh
db.dropDatabase()
db.posts.insertMany([{
    title: "Welcome to Explore Edinburgh(express test 1)",
    featuredPhoto: "/432425521",
    date: "10th September 2020, 14:25",
    tags: ["edinburgh", "explore edinburgh"],
    body:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum condimentum, quam vel porta porta, elit mauris viverra diam, et pharetra nisl lorem eget neque. Integer porttitor turpis cursus tellus vulputate cursus. Etiam ullamcorper vehicula urna, ac commodo purus dapibus eu. Duis fermentum turpis at hendrerit dictum. Donec in sapien id urna maximus accumsan. Quisque vel augue vel quam molestie sollicitudin. Quisque a purus et odio tempus viverra. Sed sodales nisi vel diam auctor blandit. Aenean ac lectus non enim facilisis sollicitudin vitae non nisl. Nullam vitae mollis dolor. Nulla sit amet mauris vitae mauris convallis scelerisque. Integer consectetur feugiat lobortis. Ut sed nunc quis sapien dictum condimentum nec nec arcu. Donec dictum a magna eget tincidunt. Pellentesque ac leo lobortis, lobortis purus in, molestie erat. Nullam sagittis, erat sed rutrum accumsan, purus sem efficitur enim, ut tempus massa magna a tortor. <br/><br/>Praesent sit amet maximus quam. Pellentesque augue nisi, convallis non ipsum sit amet, semper ornare mi. Nunc mattis tellus luctus augue cursus, non porta lectus porta. Vestibulum lacinia urna metus, in volutpat est blandit vitae. Nam non mollis sapien, aliquam gravida mi. Sed interdum in nisl vel egestas. Donec fermentum, enim sed sagittis dapibus, lectus sem mollis mi, nec placerat lectus orci nec lectus. Sed gravida varius nulla id posuere. Fusce cursus tortor in massa tristique blandit. Aenean posuere velit vitae tortor dictum aliquam. Vestibulum commodo, nunc at pretium porta, mauris erat mattis purus, nec dapibus est orci non arcu. Praesent in ligula in metus vulputate rhoncus eu eu turpis. Maecenas dapibus leo leo. Etiam suscipit finibus turpis, iaculis varius risus egestas sed. Curabitur nec sapien id arcu faucibus luctus.",
  },
  {
    title: "Welcome to Explore Edinburgh(express test 2)",
    featuredPhoto: "/43242552",
    date: "4th September 2020, 14:36",
    tags: ["edinburgh", "explore edinburgh"],
    body:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum condimentum, quam vel porta porta, elit mauris viverra diam, et pharetra nisl lorem eget neque. Integer porttitor turpis cursus tellus vulputate cursus. Etiam ullamcorper vehicula urna, ac commodo purus dapibus eu. Duis fermentum turpis at hendrerit dictum. Donec in sapien id urna maximus accumsan. Quisque vel augue vel quam molestie sollicitudin. Quisque a purus et odio tempus viverra. Sed sodales nisi vel diam auctor blandit. Aenean ac lectus non enim facilisis sollicitudin vitae non nisl. Nullam vitae mollis dolor. Nulla sit amet mauris vitae mauris convallis scelerisque. Integer consectetur feugiat lobortis. Ut sed nunc quis sapien dictum condimentum nec nec arcu. Donec dictum a magna eget tincidunt. Pellentesque ac leo lobortis, lobortis purus in, molestie erat. Nullam sagittis, erat sed rutrum accumsan, purus sem efficitur enim, ut tempus massa magna a tortor. <br/><br/>Praesent sit amet maximus quam. Pellentesque augue nisi, convallis non ipsum sit amet, semper ornare mi. Nunc mattis tellus luctus augue cursus, non porta lectus porta. Vestibulum lacinia urna metus, in volutpat est blandit vitae. Nam non mollis sapien, aliquam gravida mi. Sed interdum in nisl vel egestas. Donec fermentum, enim sed sagittis dapibus, lectus sem mollis mi, nec placerat lectus orci nec lectus. Sed gravida varius nulla id posuere. Fusce cursus tortor in massa tristique blandit. Aenean posuere velit vitae tortor dictum aliquam. Vestibulum commodo, nunc at pretium porta, mauris erat mattis purus, nec dapibus est orci non arcu. Praesent in ligula in metus vulputate rhoncus eu eu turpis. Maecenas dapibus leo leo. Etiam suscipit finibus turpis, iaculis varius risus egestas sed. Curabitur nec sapien id arcu faucibus luctus.",
  },
  {
    title: "Welcome to Explore Edinburgh(express test 3)",
    featuredPhoto: "/43242553",
    date: "15th September 2020, 14:27",
    tags: ["edinburgh", "explore edinburgh"],
    body:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum condimentum, quam vel porta porta, elit mauris viverra diam, et pharetra nisl lorem eget neque. Integer porttitor turpis cursus tellus vulputate cursus. Etiam ullamcorper vehicula urna, ac commodo purus dapibus eu. Duis fermentum turpis at hendrerit dictum. Donec in sapien id urna maximus accumsan. Quisque vel augue vel quam molestie sollicitudin. Quisque a purus et odio tempus viverra. Sed sodales nisi vel diam auctor blandit. Aenean ac lectus non enim facilisis sollicitudin vitae non nisl. Nullam vitae mollis dolor. Nulla sit amet mauris vitae mauris convallis scelerisque. Integer consectetur feugiat lobortis. Ut sed nunc quis sapien dictum condimentum nec nec arcu. Donec dictum a magna eget tincidunt. Pellentesque ac leo lobortis, lobortis purus in, molestie erat. Nullam sagittis, erat sed rutrum accumsan, purus sem efficitur enim, ut tempus massa magna a tortor. <br/><br/>Praesent sit amet maximus quam. Pellentesque augue nisi, convallis non ipsum sit amet, semper ornare mi. Nunc mattis tellus luctus augue cursus, non porta lectus porta. Vestibulum lacinia urna metus, in volutpat est blandit vitae. Nam non mollis sapien, aliquam gravida mi. Sed interdum in nisl vel egestas. Donec fermentum, enim sed sagittis dapibus, lectus sem mollis mi, nec placerat lectus orci nec lectus. Sed gravida varius nulla id posuere. Fusce cursus tortor in massa tristique blandit. Aenean posuere velit vitae tortor dictum aliquam. Vestibulum commodo, nunc at pretium porta, mauris erat mattis purus, nec dapibus est orci non arcu. Praesent in ligula in metus vulputate rhoncus eu eu turpis. Maecenas dapibus leo leo. Etiam suscipit finibus turpis, iaculis varius risus egestas sed. Curabitur nec sapien id arcu faucibus luctus.",
  }
])
